import os

ROOT_DIR = os.path.join(os.path.abspath(os.path.dirname(__file__)), '..', '..')
DATA_FOLDER = os.path.join(ROOT_DIR, 'data')
INSPECTED_DATA_FOLDER = os.path.join(DATA_FOLDER, 'inspected')
RESULTS_DATA_FOLDER = os.path.join(DATA_FOLDER, 'results')
CORPORA_FOLDER = os.path.join(INSPECTED_DATA_FOLDER, 'corpora')
METRIC_EVALUATION_FOLDER = os.path.join(INSPECTED_DATA_FOLDER, 'metric_evaluation')
DECODED_OUTPUTS_FOLDER = os.path.join(INSPECTED_DATA_FOLDER, 'decoded_outputs')
MULTIPROCESSING_DATA_FOLDER = os.path.join(INSPECTED_DATA_FOLDER, 'multiprocessing')
TUNING_FOLDER = os.path.join(INSPECTED_DATA_FOLDER, 'tuning')
TUNING_RAW_FOLDER = os.path.join(TUNING_FOLDER, 'raw')
LOGS_FOLDER = os.path.join(INSPECTED_DATA_FOLDER, 'logs')
AUGMENTATION_FOLDER =os.path.join(INSPECTED_DATA_FOLDER, 'augmentation')
PRETRAINING_FOLDER =os.path.join(INSPECTED_DATA_FOLDER, 'pretraining')
