BASE_DIR_OUTPUT = 'BASE_DIR_OUTPUT'
BASE_DIR_CORPUS = 'BASE_DIR_CORPUS'
BASE_DIR_SCRIPTS = 'BASE_DIR_SCRIPTS'
BASE_DIR_VOCAB = 'BASE_DIR_VOCAB'
BASE_DIR_ARTIFACTS = 'BASE_DIR_ARTIFACTS'

ENVIRONMENT_VARIABLES = [
    BASE_DIR_OUTPUT,
    BASE_DIR_CORPUS,
    BASE_DIR_SCRIPTS,
]